#EU

#USUARIOS
USUARIOS = "SELECT DISTINCT NOMBRE_USUARIO, ID_SECTOR_INTERNO FROM TRACK_SADE.SADE_SECTOR_USUARIO WHERE ESTADO_REGISTRO = 1"

#USUARIOS_Q
USUARIOS_Q = "SELECT COUNT(DISTINCT NOMBRE_USUARIO) FROM TRACK_SADE.SADE_SECTOR_USUARIO WHERE ESTADO_REGISTRO = 1"

#SECTOR_INTERNO
SECTOR_INTERNO = "SELECT ID_SECTOR_INTERNO, CODIGO_REPARTICION, CODIGO_SECTOR_INTERNO, NOMBRE_SECTOR_INTERNO FROM TRACK_SADE.SADE_SECTOR_INTERNO WHERE ESTADO_REGISTRO = 1"

#SECTOR_INTERNO_Q
SECTOR_INTERNO_Q = "SELECT COUNT(*) FROM TRACK_SADE.SADE_SECTOR_INTERNO WHERE ESTADO_REGISTRO = 1"

#REPARTICION
REPARTICION = "SELECT ID_REPARTICION, CODIGO_REPARTICION, NOMBRE_REPARTICION, REP_PADRE FROM TRACK_SADE.SADE_REPARTICION WHERE ESTADO_REGISTRO = 1"

#REPARTICION_Q
REPARTICION_Q = "SELECT COUNT(*) FROM TRACK_SADE.SADE_REPARTICION WHERE ESTADO_REGISTRO = 1"

#MIGRACIONES
MIGRACIONES = "SELECT DISTINCT TOKEN, TIPO_MIGRACION, USUARIO_SOLICITANTE, USUARIO, ORIGEN_REPARTICION, ORIGEN_SECTOR, DESTINO_REPARTICION, DESTINO_SECTOR, FECHA_CREACION FROM EU_SADE.MIG_TAREA"


#GEDO

#COMUNICACION_ENVIADA
COMUNICACION_ENVIADA = "SELECT FECHA_CREACION, USUARIO_CREADOR, ID_DOCUMENTO FROM GEDO_SADE.CCOO_COMUNICACION"

#COMUNICACION_ENVIADA_Q
COMUNICACION_ENVIADA_Q = "SELECT COUNT(*) FROM GEDO_SADE.CCOO_COMUNICACION"

#COMUNICACION_BANDEJA
COMUNICACION_BANDEJA = "SELECT NOMBRE_USUARIO, LEIDO, ID_COMUNICACION FROM GEDO_SADE.CCOO_COMUNICACION_DESTINO WHERE FECHA_ELIMINACION_BANDEJA IS NULL" 

#COMUNICACION_BANDEJA_Q
COMUNICACION_BANDEJA_Q = "SELECT COUNT(*) FROM GEDO_SADE.CCOO_COMUNICACION_DESTINO"

#DOCUMENTO
DOCUMENTO = "SELECT ID, NUMERO, ANIO, REPARTICION, MOTIVO, USUARIOGENERADOR, FECHACREACION, TIPO, SISTEMAINICIADOR, TIPORESERVA FROM GEDO_SADE.GEDO_DOCUMENTO"

#DOCUMENTO_Q
DOCUMENTO_Q = "SELECT COUNT(*) FROM GEDO_SADE.GEDO_DOCUMENTO"

#ACTO_ADMINISTRATIVO
ACTO_ADMINISTRATIVO = "SELECT CODIGOREPARTICION, ANIO, NUMERO, TIPODOCUMENTO FROM GEDO_SADE.GEDO_NUMERACIONESPECIAL"

#ACTO_ADMINISTRATIVO_Q
ACTO_ADMINISTRATIVO_Q=  "SELECT COUNT(*) FROM GEDO_SADE.GEDO_NUMERACIONESPECIAL"

#TIPO_DOCUMENTO
TIPO_DOCUMENTO = "SELECT ID, ACRONIMO, NOMBRE, ESTADO FROM GEDO_SADE.GEDO_TIPODOCUMENTO"

#TIPO_DOCUMENTO_Q
TIPO_DOCUMENTO_Q = "SELECT COUNT(*) FROM GEDO_SADE.GEDO_TIPODOCUMENTO"

#BANDEJA_GEDO
BANDEJA_GEDO = "SELECT ASSIGNEE_, CREATE_ FROM GEDO_SADE.JBPM4_TASK"

#BANDEJA_GEDO_Q
BANDEJA_GEDO_Q = "SELECT COUNT(*) FROM GEDO_SADE.JBPM4_TASK"

# EE

#EXPEDIENTE
EXPEDIENTE = "SELECT DESCRIPCION, ID_TRATA, ANIO, CODIGO_REPARTICION_USUARIO, USUARIO_CREADOR, ESTADO, SISTEMA_CREADOR, SISTEMA_APODERADO FROM EE_SADE.EE_EXPEDIENTE_ELECTRONICO"

#EXPEDIENTE_Q
EXPEDIENTE_Q = "SELECT COUNT(*) FROM EE_SADE.EE_EXPEDIENTE_ELECTRONICO"

#EXPEDIENTE_DOCUMENTO_Q
EXPEDIENTE_DOCUMENTO_Q = "SELECT COUNT(ID) FROM EE_SADE.EE_EXPEDIENTE_DOCUMENTOS"

#HISTORIAL_Q
HISTORIAL_Q = "SELECT COUNT(ID_EXPEDIENTE) FROM EE_SADE.HISTORIALOPERACION"

#USUARIO_ASIGNADO
USUARIO_ASIGNADO = "SELECT ASSIGNEE_, EXECUTION_ID_, DBID_ FROM EE_SADE.JBPM4_TASK"

#USUARIO_ASIGNADO_Q
USUARIO_ASIGNADO_Q = "SELECT COUNT(*) FROM EE_SADE.JBPM4_TASK"

#BUZON_GRUPAL
BUZON_GRUPAL = "SELECT TASK_, GROUPID_ FROM EE_SADE.JBPM4_PARTICIPATION"

#BUZON_GRUPAL_Q
BUZON_GRUPAL_Q = "SELECT COUNT(*) FROM EE_SADE.JBPM4_PARTICIPATION"

#LOYS

#EXPEDIENTE_LOYS
EXPEDIENTE_LOYS = "SELECT ID, CODEXPEDIENTE, ID_REPARTICIONDESTINO, ID_REPARTICIONORIGEN, ID_POSTULANTE_TAD, TIPO_CONTRATACION, ID_REPARTICION_DESEMPENIO FROM LOYS_MAN_SADE.ST_EXPEDIENTE"

#EXPEDIENTE_LOYS_Q
EXPEDIENTE_LOYS_Q = "SELECT COUNT(*) FROM LOYS_MAN_SADE.ST_EXPEDIENTE"

#PROCEDIMIENTO
PROCEDIMIENTO = "SELECT ID, EXPEDIENTE FROM LOYS_MAN_SADE.ST_PROCEDIMIENTO"

#ACTIVIDAD
ACTIVIDAD = "SELECT ID_PROCEDIMIENTO, TASKINSTANCEID FROM LOYS_MAN_SADE.ST_ACTIVIDAD"

#TASKINSTANCE
TASKINSTANCE = "SELECT NAME_, CREATE_, END_ FROM LOYS_MAN_SADE.JBPM_TASKINSTANCE"

#TASKACTORPOOL
TASKACTORPOOL = "SELECT TASKINSTANCE_, POOLEDACTOR_ FROM LOYS_MAN_SADE.JBPM_TASKACTORPOOL"

#POOLEDACTOR
POOLEDACTOR = "SELECT ID_, ACTORID_ FROM LOYS_MAN_SADE.JBPM_POOLEDACTOR"

#DATOS_POSTULANTE
DATOS_POSTULANTE = "SELECT ID_POSTULANTE_TAD, NRO_CUIT, NOMBRE, APELLIDO, SEXO, NACIONALIDAD, FECHA_NACIMIENTO FROM LOYS_MAN_SADE.LOYS_POSTULANTE_TAD"
