datos = {
        "20335736479": {
          "0": "GUP",
          "1": "ARCH",
          "2": "SADE",
          "3": "RLM",
          "4": "RIB",
          "5": "FFCC",
          "6": "DDJJ",
          "7": "AFJG",
          "8": "PSOC",
          "9": "EE",
          "10": "RIC",
          "11": "LOYS",
          "12": "TRACK",
          "13": "LE",
          "14": "GEDO",
          "15": "EU",
          "16": "RCE",
          "17": "DIGESTO",
          "18": "LUNNA"
        },
          "20334983685": {
            "0": "GUP",
            "1": "ARCH",
            "2": "SADE",
            "3": "RLM",
            "4": "RIB",
            "5": "FFCC",
            "6": "DDJJ",
            "7": "AFJG",
            "8": "PSOC",
            "9": "EE",
            "10": "RIC",
            "11": "LOYS",
            "12": "TRACK",
            "13": "LE",
            "14": "GEDO",
            "15": "EU",
            "16": "RCE",
            "17": "DIGESTO",
            "18": "LUNNA"
          }
          ,
        "20382930909":{
          "0": "GUP",
          "1": "ARCH",
          "2": "SADE",
          "3": "RLM",
          "4": "RIB",
          "5": "FFCC",
          "6": "DDJJ",
          "7": "AFJG",
          "8": "PSOC",
          "9": "EE",
          "10": "RIC",
          "11": "LOYS",
          "12": "TRACK",
          "13": "LE",
          "14": "GEDO",
          "15": "EU",
          "16": "RCE",
          "17": "DIGESTO",
          "18": "LUNNA"
        },
        "todos":{
            "0": "GUP",
            "1": "ARCH",
            "2": "SADE",
            "3": "RLM",
            "4": "RIB",
            "5": "FFCC",
            "6": "DDJJ",
            "7": "AFJG",
            "8": "PSOC",
            "9": "EE",
            "10": "RIC",
            "11": "LOYS",
            "12": "TRACK",
            "13": "LE",
            "14": "GEDO",
            "15": "EU",
            "16": "RCE",
            "17": "DIGESTO",
            "18": "LUNNA"
          },
          "20955554095":{
            "0": "GUP",
            "1": "ARCH",
            "2": "SADE",
            "3": "RLM",
            "4": "RIB",
            "5": "FFCC",
            "6": "DDJJ",
            "7": "AFJG",
            "8": "PSOC",
            "9": "EE",
            "10": "RIC",
            "11": "LOYS",
            "12": "TRACK",
            "13": "LE",
            "14": "GEDO",
            "15": "EU",
            "16": "RCE",
            "17": "DIGESTO",
            "18": "LUNNA"
          },
          "27360657006":{
            "0": "GUP",
            "1": "ARCH",
            "2": "SADE",
            "3": "RLM",
            "4": "RIB",
            "5": "FFCC",
            "6": "DDJJ",
            "7": "AFJG",
            "8": "PSOC",
            "9": "EE",
            "10": "RIC",
            "11": "LOYS",
            "12": "TRACK",
            "13": "LE",
            "14": "GEDO",
            "15": "EU",
            "16": "RCE",
            "17": "DIGESTO",
            "18": "LUNNA"
          },
          "27367214029":{
            "0": "GUP",
            "1": "ARCH",
            "2": "SADE",
            "3": "RLM",
            "4": "RIB",
            "5": "FFCC",
            "6": "DDJJ",
            "7": "AFJG",
            "8": "PSOC",
            "9": "EE",
            "10": "RIC",
            "11": "LOYS",
            "12": "TRACK",
            "13": "LE",
            "14": "GEDO",
            "15": "EU",
            "16": "RCE",
            "17": "DIGESTO",
            "18": "LUNNA"
          }

    
    }