datos = [{"20335736479":{    
        "permisos":[
            "permisos-usuario",
            "modificar-permisos"
            ],
        "operaciones":[
            "incidentes",
            "regulatorios",
            "servicios"
            ]
        },
    "20382930909":{    
        "permisos":[
            "permisos-usuario",
            "modificar-permisos"
            ],
        "operaciones":[
            "incidentes",
            "regulatorios",
            "servicios"
            ]
        },
    "20955554095":{    
            "permisos":[
                "permisos-usuario",
                "modificar-permisos"
                ],
            "operaciones":[
                "incidentes",
                "regulatorios",
                "servicios"
                ]
            },
    "27360657006":{    
        "permisos":[
            "permisos-usuario",
            "modificar-permisos"
            ],
        "operaciones":[
            "incidentes",
            "regulatorios",
            "servicios"
            ]
        },
    "27367214029":{    
        "permisos":[
            "permisos-usuario",
            "modificar-permisos"
            ],
        "operaciones":[
            "incidentes",
            "regulatorios",
            "servicios"
            ]
        }, 
    "20334983685":{    
        "permisos":[
            "permisos-usuario",
            "modificar-permisos"
            ],
        "operaciones":[
            "incidentes",
            "regulatorios",
            "servicios"
            ]
        } 
    }
]